[package]
name = "httphunter-desktop"
version = "0.1.0"
edition = "2021"
description = "Desktop application for httphunter"
license = "MIT"

[workspace]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
flate2 = "1"
hunter-core = { path = "../../crates/hunter-core" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
